// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	TAuthInfo
	TGetAuthArg
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import sync "sync"
import gob "encoding/gob"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TAuthInfo struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age              *int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Sex              *int32  `protobuf:"varint,3,opt,name=sex" json:"sex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

var gTAuthInfoDummy TAuthInfo
var poolTAuthInfo = sync.Pool{
	New: func() interface{} {
		return new(TAuthInfo)
	},
}

func NewTAuthInfo() *TAuthInfo {
	obj := poolTAuthInfo.Get().(*TAuthInfo)
	obj.Reset()
	return obj
}
func (m *TAuthInfo) Put() {
	poolTAuthInfo.Put(m)
}
func (m *TAuthInfo) Reset()         { *m = gTAuthInfoDummy }
func (m *TAuthInfo) String() string { return proto.CompactTextString(m) }
func (*TAuthInfo) ProtoMessage()    {}

func (m *TAuthInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TAuthInfo) SetName(v string) {
	if m != nil {
		if m.Name != nil {
			*m.Name = v
		} else {
			m.Name = &v
		}
	}
}

func (m *TAuthInfo) GetAge() int32 {
	if m != nil && m.Age != nil {
		return *m.Age
	}
	return 0
}

func (m *TAuthInfo) SetAge(v int32) {
	if m != nil {
		if m.Age != nil {
			*m.Age = v
		} else {
			m.Age = &v
		}
	}
}

func (m *TAuthInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *TAuthInfo) SetSex(v int32) {
	if m != nil {
		if m.Sex != nil {
			*m.Sex = v
		} else {
			m.Sex = &v
		}
	}
}

type TGetAuthArg struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

var gTGetAuthArgDummy TGetAuthArg
var poolTGetAuthArg = sync.Pool{
	New: func() interface{} {
		return new(TGetAuthArg)
	},
}

func NewTGetAuthArg() *TGetAuthArg {
	obj := poolTGetAuthArg.Get().(*TGetAuthArg)
	obj.Reset()
	return obj
}
func (m *TGetAuthArg) Put() {
	poolTGetAuthArg.Put(m)
}
func (m *TGetAuthArg) Reset()         { *m = gTGetAuthArgDummy }
func (m *TGetAuthArg) String() string { return proto.CompactTextString(m) }
func (*TGetAuthArg) ProtoMessage()    {}

func (m *TGetAuthArg) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TGetAuthArg) SetName(v string) {
	if m != nil {
		if m.Name != nil {
			*m.Name = v
		} else {
			m.Name = &v
		}
	}
}

func init() {
	proto.RegisterType((*TAuthInfo)(nil), "pb.TAuthInfo")
	gob.Register((*TAuthInfo)(nil))
	proto.RegisterType((*TGetAuthArg)(nil), "pb.TGetAuthArg")
	gob.Register((*TGetAuthArg)(nil))
}
