// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: memo.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TMemo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Text      string `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
}

func (x *TMemo) Reset() {
	*x = TMemo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_memo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TMemo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMemo) ProtoMessage() {}

func (x *TMemo) ProtoReflect() protoreflect.Message {
	mi := &file_memo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMemo.ProtoReflect.Descriptor instead.
func (*TMemo) Descriptor() ([]byte, []int) {
	return file_memo_proto_rawDescGZIP(), []int{0}
}

func (x *TMemo) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *TMemo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TMemo) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TMemoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Memos []*TMemo `protobuf:"bytes,1,rep,name=memos,proto3" json:"memos,omitempty"`
}

func (x *TMemoList) Reset() {
	*x = TMemoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_memo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TMemoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMemoList) ProtoMessage() {}

func (x *TMemoList) ProtoReflect() protoreflect.Message {
	mi := &file_memo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMemoList.ProtoReflect.Descriptor instead.
func (*TMemoList) Descriptor() ([]byte, []int) {
	return file_memo_proto_rawDescGZIP(), []int{1}
}

func (x *TMemoList) GetMemos() []*TMemo {
	if x != nil {
		return x.Memos
	}
	return nil
}

var File_memo_proto protoreflect.FileDescriptor

var file_memo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x49, 0x0a, 0x05, 0x54, 0x4d, 0x65, 0x6d, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x22, 0x2c, 0x0a, 0x09, 0x54,
	0x4d, 0x65, 0x6d, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x6d, 0x65, 0x6d, 0x6f,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x4d, 0x65,
	0x6d, 0x6f, 0x52, 0x05, 0x6d, 0x65, 0x6d, 0x6f, 0x73, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_memo_proto_rawDescOnce sync.Once
	file_memo_proto_rawDescData = file_memo_proto_rawDesc
)

func file_memo_proto_rawDescGZIP() []byte {
	file_memo_proto_rawDescOnce.Do(func() {
		file_memo_proto_rawDescData = protoimpl.X.CompressGZIP(file_memo_proto_rawDescData)
	})
	return file_memo_proto_rawDescData
}

var file_memo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_memo_proto_goTypes = []interface{}{
	(*TMemo)(nil),     // 0: pb.TMemo
	(*TMemoList)(nil), // 1: pb.TMemoList
}
var file_memo_proto_depIdxs = []int32{
	0, // 0: pb.TMemoList.memos:type_name -> pb.TMemo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_memo_proto_init() }
func file_memo_proto_init() {
	if File_memo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_memo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TMemo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_memo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TMemoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_memo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_memo_proto_goTypes,
		DependencyIndexes: file_memo_proto_depIdxs,
		MessageInfos:      file_memo_proto_msgTypes,
	}.Build()
	File_memo_proto = out.File
	file_memo_proto_rawDesc = nil
	file_memo_proto_goTypes = nil
	file_memo_proto_depIdxs = nil
}

var TMemoPool = sync.Pool{
	New: func() interface{} {
		return new(TMemo)
	},
}

func NewTMemo() *TMemo {
	return TMemoPool.Get().(*TMemo)
}

func (x *TMemo) Put() {
	*x = TMemo{}
	TMemoPool.Put(x)
}

var TMemoListPool = sync.Pool{
	New: func() interface{} {
		return new(TMemoList)
	},
}

func NewTMemoList() *TMemoList {
	return TMemoListPool.Get().(*TMemoList)
}

func (x *TMemoList) Put() {
	*x = TMemoList{}
	TMemoListPool.Put(x)
}

var TMemoPool = sync.Pool{
	New: func() interface{} {
		return new(TMemo)
	},
}

//`````
func NewTMemo() *TMemo {
	return TMemoPool.Get().(*TMemo)
}

func (x *TMemo) Put() {
	*x = TMemo{}
	TMemoPool.Put(x)
}

var TMemoListPool = sync.Pool{
	New: func() interface{} {
		return new(TMemoList)
	},
}

//`````
func NewTMemoList() *TMemoList {
	return TMemoListPool.Get().(*TMemoList)
}

func (x *TMemoList) Put() {
	*x = TMemoList{}
	TMemoListPool.Put(x)
}
