// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: ret.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TAppRet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *TAppRet) Reset() {
	*x = TAppRet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ret_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TAppRet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TAppRet) ProtoMessage() {}

func (x *TAppRet) ProtoReflect() protoreflect.Message {
	mi := &file_ret_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TAppRet.ProtoReflect.Descriptor instead.
func (*TAppRet) Descriptor() ([]byte, []int) {
	return file_ret_proto_rawDescGZIP(), []int{0}
}

func (x *TAppRet) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TAppRet) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TAppRet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_ret_proto protoreflect.FileDescriptor

var file_ret_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22,
	0x43, 0x0a, 0x07, 0x54, 0x41, 0x70, 0x70, 0x52, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67,
	0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ret_proto_rawDescOnce sync.Once
	file_ret_proto_rawDescData = file_ret_proto_rawDesc
)

func file_ret_proto_rawDescGZIP() []byte {
	file_ret_proto_rawDescOnce.Do(func() {
		file_ret_proto_rawDescData = protoimpl.X.CompressGZIP(file_ret_proto_rawDescData)
	})
	return file_ret_proto_rawDescData
}

var file_ret_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ret_proto_goTypes = []interface{}{
	(*TAppRet)(nil), // 0: pb.TAppRet
}
var file_ret_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ret_proto_init() }
func file_ret_proto_init() {
	if File_ret_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ret_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TAppRet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ret_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ret_proto_goTypes,
		DependencyIndexes: file_ret_proto_depIdxs,
		MessageInfos:      file_ret_proto_msgTypes,
	}.Build()
	File_ret_proto = out.File
	file_ret_proto_rawDesc = nil
	file_ret_proto_goTypes = nil
	file_ret_proto_depIdxs = nil
}

var TAppRetPool = sync.Pool{
	New: func() interface{} {
		return new(TAppRet)
	},
}

func NewTAppRet() *TAppRet {
	return TAppRetPool.Get().(*TAppRet)
}

func (x *TAppRet) Put() {
	*x = TAppRet{}
	TAppRetPool.Put(x)
}
